services:
  - type: web
    name: my-lps-game-app # Beri nama sesuai keinginan Anda
    env: php
    repo: https://github.com/Benylaode/lpsgame.git # Ganti dengan URL repo Anda
    branch: main # Sesuaikan dengan branch Anda (misalnya main atau master)
    rootDir: lps_game # INI YANG PENTING: Render akan bekerja di dalam folder ini
    buildCommand: composer install # Hanya jika Anda punya composer.json di lps_game/
    startCommand: php-fpm
    routes:
      # INI PENTING UNTUK MENGARAHKAN KE FOLDER PUBLIC
      - type: redirect
        source: /(.*)
        destination: /public/$1
